# Create a folder for plots generated from XVG files
output_dir <- "plots"
dir.create(output_dir, showWarnings = FALSE)

# Remove Grace formatting commands from text
clean_grace_text <- function(text) {
  if (is.null(text) || is.na(text)) {
    return("")
  }

  # Convert superscript and subscript formatting
  text <- gsub("\\\\S([^\\\\]+)\\\\N", "^\\1", text, perl = TRUE)
  text <- gsub("\\\\s([^\\\\]+)\\\\N", "_\\1", text, perl = TRUE)

  # Remove font change commands
  text <- gsub("\\\\f\\{[^}]*\\}", "", text, perl = TRUE)

  # Remove remaining Grace formatting tags
  text <- gsub("\\\\N", "", text)

  text
}

# Extract text placed between quotation marks
extract_metadata <- function(lines, pattern, default_value) {
  matching_lines <- grep(pattern, lines, value = TRUE)

  if (length(matching_lines) == 0) {
    return(default_value)
  }

  value <- sub('.*"(.*)".*', "\\1", matching_lines[1])
  clean_grace_text(value)
}

# Create one plot from one XVG file
plot_xvg <- function(file_path) {

  message("Processing: ", file_path)

  lines <- readLines(file_path, warn = FALSE)

  file_name <- tools::file_path_sans_ext(basename(file_path))

  # Read metadata generated by GROMACS
  graph_title <- extract_metadata(
    lines,
    "^@\\s+title\\s+",
    file_name
  )

  x_label <- extract_metadata(
    lines,
    "^@\\s+xaxis\\s+label\\s+",
    "X"
  )

  y_label <- extract_metadata(
    lines,
    "^@\\s+yaxis\\s+label\\s+",
    "Y"
  )

  # Read series legends
  legend_lines <- grep(
    "^@\\s+s[0-9]+\\s+legend\\s+",
    lines,
    value = TRUE
  )

  legends <- sub('.*"(.*)".*', "\\1", legend_lines)
  legends <- vapply(
    legends,
    clean_grace_text,
    character(1)
  )

  # Keep only numerical data
  data_lines <- lines[
    !grepl("^\\s*[@#]", lines) &
      trimws(lines) != "" &
      trimws(lines) != "&"
  ]

  if (length(data_lines) == 0) {
    warning("No numerical data in the file: ", file_path)
    return(invisible(NULL))
  }

  data <- read.table(
    text = data_lines,
    header = FALSE,
    fill = TRUE
  )

  if (ncol(data) < 2) {
    warning("The file has fewer than two columns: ", file_path)
    return(invisible(NULL))
  }

  number_of_series <- ncol(data) - 1

  # Plot only the hydrogen-bond series from hbnum.xvg
  if (tolower(file_name) == "hbnum") {
    visible_series <- 0
  } else {
    visible_series <- 0:(number_of_series - 1)
  }

  # The first column contains x values
  visible_columns <- visible_series + 2

  output_file <- file.path(
    output_dir,
    paste0(file_name, ".png")
  )

  png(
    filename = output_file,
    width = 1800,
    height = 1200,
    res = 200
  )

  matplot(
    x = data[[1]],
    y = data[, visible_columns, drop = FALSE],
    type = "l",
    lty = 1,
    lwd = 2,
    xlab = x_label,
    ylab = y_label,
    main = graph_title
  )

  grid()

  # Add a legend when legend information is available
  if (
    length(legend_lines) > 0 &&
    length(legends) >= max(visible_series + 1)
  ) {
    legend(
      "topright",
      legend = legends[visible_series + 1],
      lty = 1,
      lwd = 2,
      bty = "n"
    )
  }

  dev.off()

  message("Saved: ", output_file)
}

# Find all XVG files in the current folder
xvg_files <- list.files(
  path = ".",
  pattern = "\\.xvg$",
  full.names = TRUE
)

# Create a plot for every XVG file
invisible(lapply(xvg_files, plot_xvg))

message("Diagrams are saved in the folder: ", output_dir)
